#!/bin/bash
#
#       /etc/rc.d/init.d/hadoop-yarn
#
# chkconfig: 345 70 70
# description: Handling hadoop-yarn


# Source function library.
. /etc/init.d/functions
. /etc/profile.d/java-env.sh
. /etc/profile.d/hadoop-env.sh

start() {
        echo -n "Starting hadoop-dfs"
	${HADOOP_HOME}/sbin/start-yarn.sh
}

stop() {
        echo -n $"Stopping hadoop-yarn"
	${HADOOP_HOME}/sbin/stop-yarn.sh
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: <servicename> {start|stop|restart}"
        exit 1
        ;;
esac
exit $?

